package co.edu.escuelaing.techcup.identity.infrastructure.adapter.in.rest.controller;

import co.edu.escuelaing.techcup.identity.domain.model.User;
import co.edu.escuelaing.techcup.identity.domain.port.in.CreateCredentialsUseCase;
import co.edu.escuelaing.techcup.identity.domain.port.in.GetUserEmailUseCase;
import co.edu.escuelaing.techcup.identity.domain.port.in.UpdateCredentialsUseCase;
import co.edu.escuelaing.techcup.identity.infrastructure.adapter.in.rest.dto.request.CreateCredentialRequest;
import co.edu.escuelaing.techcup.identity.infrastructure.adapter.in.rest.dto.request.UpdateRoleRequest;
import co.edu.escuelaing.techcup.identity.infrastructure.adapter.in.rest.dto.request.UpdateStatusRequest;
import co.edu.escuelaing.techcup.identity.infrastructure.adapter.in.rest.dto.response.MessageResponse;
import co.edu.escuelaing.techcup.identity.infrastructure.adapter.in.rest.dto.response.UserEmailResponse;
import co.edu.escuelaing.techcup.identity.infrastructure.adapter.in.rest.dto.response.UserResponse;
import co.edu.escuelaing.techcup.identity.infrastructure.mapper.UserMapper;
import io.swagger.v3.oas.annotations.Hidden;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.UUID;

/**
 * Internal endpoint consumed by users-players-service for credential creation
 * during Student User Registration, Guest User Registration, and Graduate User Registration.
 */
@RestController
@RequestMapping("/api/v1/internal/credentials")
@Tag(name = "Internal", description = "Internal endpoints for inter-service communication. " +
        "Consumed by users-players-service for credential, role, and account status management. " +
        "These endpoints MUST NOT be exposed to end users; they are protected at the internal network level.")
@Hidden
@RequiredArgsConstructor
public class InternalCredentialController {

    private final CreateCredentialsUseCase createCredentialsUseCase;
    private final UpdateCredentialsUseCase updateCredentialsUseCase;
    private final GetUserEmailUseCase getUserEmailUseCase;
    private final UserMapper userMapper;

    @PostMapping
    @Operation(
            summary = "Create credentials for user registered in users-players-service",
            description = "Creates authentication credentials (email + BCrypt-hashed password) for a user who was " +
                    "previously registered in users-players-service. Receives the userId generated by users-players-service " +
                    "(source of truth), email, plain text password, full name, " +
                    "user type, and role. The account is created in ACTIVE state. If the email already exists, returns 409 Conflict. " +
                    "Sends OTP to the user's email. Logs CREDENTIALS_CREATED audit event."
    )
    @ApiResponses({
            @ApiResponse(responseCode = "201", description = "Credentials created successfully. Returns user data."),
            @ApiResponse(responseCode = "400", description = "Invalid data: empty userId, empty/invalid email, empty password, empty name, null type/role."),
            @ApiResponse(responseCode = "409", description = "Credentials already exist for the provided email.")
    })
    public ResponseEntity<UserResponse> createCredentials(@Valid @RequestBody CreateCredentialRequest request) {
        User saved = createCredentialsUseCase.createCredentials(
                request.getUserId(),
                request.getEmail(),
                request.getPassword(),
                request.getFullName(),
                request.getUserType(),
                request.getRole()
        );
        return ResponseEntity.status(HttpStatus.CREATED).body(userMapper.toResponse(saved));
    }

    @PutMapping("/{userId}/role")
    @Operation(
            summary = "Update user role",
            description = "Updates the authentication role of a user in Identity Service. " +
                    "Consumed by users-players-service when a player is promoted to captain (Captain Promotion) " +
                    "or by teams-service when captaincy is transferred (Captaincy Transfer). " +
                    "The change takes effect in the next JWT generated upon login. " +
                    "Logs ROLE_UPDATED audit event."
    )
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Role updated successfully."),
            @ApiResponse(responseCode = "400", description = "Null or invalid role."),
            @ApiResponse(responseCode = "404", description = "No credentials found for the provided userId.")
    })
    public ResponseEntity<MessageResponse> updateRole(
            @Parameter(description = "User ID (generated by users-players-service)")
            @PathVariable UUID userId,
            @Valid @RequestBody UpdateRoleRequest request) {
        updateCredentialsUseCase.updateRole(userId, request.getRole());
        return ResponseEntity.ok(MessageResponse.builder()
                .message("Role updated to " + request.getRole())
                .build());
    }

    @PutMapping("/{userId}/status")
    @Operation(
            summary = "Update user account status",
            description = "Updates the account status of a user in Identity Service. " +
                    "Consumed by users-players-service when an Admin disables a user (User Disabling). " +
                    "An INACTIVE account cannot log in. " +
                    "Logs STATUS_UPDATED audit event."
    )
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Status updated successfully."),
            @ApiResponse(responseCode = "400", description = "Null or invalid status."),
            @ApiResponse(responseCode = "404", description = "No credentials found for the provided userId.")
    })
    public ResponseEntity<MessageResponse> updateStatus(
            @Parameter(description = "User ID (generated by users-players-service)")
            @PathVariable UUID userId,
            @Valid @RequestBody UpdateStatusRequest request) {
        updateCredentialsUseCase.updateStatus(userId, request.getStatus());
        return ResponseEntity.ok(MessageResponse.builder()
                .message("Status updated to " + request.getStatus())
                .build());
    }

    @GetMapping("/{userId}/email")
    @Operation(
            summary = "Get user email by userId",
            description = "Resolves the actual email address associated with a userId. " +
                    "Consumed by am-notification-service to send notification emails, " +
                    "since the events it receives only carry the recipientId (UUID), never the email. " +
                    "Protected by internal API key (X-Internal-Api-Key header), unlike other " +
                    "internal endpoints in this controller."
    )
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Email found successfully."),
            @ApiResponse(responseCode = "401", description = "Missing or invalid internal API key."),
            @ApiResponse(responseCode = "404", description = "No credentials found for the provided userId.")
    })
    public ResponseEntity<UserEmailResponse> getUserEmail(
            @Parameter(description = "User ID (generated by users-players-service)")
            @PathVariable UUID userId) {
        String email = getUserEmailUseCase.getEmailByUserId(userId);
        return ResponseEntity.ok(UserEmailResponse.builder()
                .email(email)
                .build());
    }
}
