package co.edu.escuelaing.techcup.identity.infrastructure.adapter.in.rest.dto.request;

import co.edu.escuelaing.techcup.identity.domain.enums.UserRole;
import co.edu.escuelaing.techcup.identity.domain.enums.UserType;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.UUID;

@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Schema(description = "Internal DTO for credential creation from users-players-service. " +
        "Usado durante el registro de estudiantes (Registro de Estudiante), invitados (Registro de Invitado), egresados (Registro de Egresado), " +
        "administradores (Creación de Usuario Admin y Organizador) y árbitros (Creación de Cuenta de Árbitro).")
public class CreateCredentialRequest {

    @NotNull(message = "User ID is required")
    @Schema(description = "User ID generated by users-players-service (source of truth)", example = "3fa85f64-5717-4562-b3fc-2c963f66afa6")
    private UUID userId;

    @NotBlank(message = "Email is required")
    @Email(message = "Invalid email format")
    @Schema(description = "User email (institucional o Gmail según tipo)", example = "estudiante@escuelaing.edu.co")
    private String email;

    @NotBlank(message = "Password is required")
    @Schema(description = "Plain text password (will be stored with BCrypt hash)", example = "Password123!")
    private String password;

    @NotBlank(message = "Full name is required")
    @Schema(description = "User full name", example = "Ada Lovelace")
    private String fullName;

    @NotNull(message = "User type is required")
    @Schema(description = "User type based on their relationship with the institution", example = "STUDENT",
            allowableValues = {"STUDENT", "GUEST", "GRADUATE", "ADMIN", "ORGANIZER", "REFEREE"})
    private UserType userType;

    @NotNull(message = "Role is required")
    @Schema(description = "User role in the TechCup platform", example = "PLAYER",
            allowableValues = {"PLAYER", "CAPTAIN", "REFEREE", "ORGANIZER", "ADMIN"})
    private UserRole role;
}
