package co.edu.escuelaing.techcup.identity.domain.port.in;

import co.edu.escuelaing.techcup.identity.domain.enums.UserRole;
import co.edu.escuelaing.techcup.identity.domain.enums.UserType;
import co.edu.escuelaing.techcup.identity.domain.model.User;

/**
 * Internal port for inter-service credential creation.
 * Called by users-players-service during any user registration (TC-01 through TC-05).
 * The userId is generated by users-players-service (source of truth for user data).
 */
public interface CreateCredentialsUseCase {

    User createCredentials(String userId, String email, String password, String fullName,
                           UserType userType, UserRole role);
}
