package co.edu.escuelaing.techcup.identity.document;

public enum AuditEventType {
    USER_REGISTERED,
    USER_REGISTRATION_FAILED,
    OTP_SENT,
    OTP_VERIFIED,
    OTP_VERIFICATION_FAILED,
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    GMAIL_LOGIN_STARTED,
    GMAIL_LOGIN_SUCCESS,
    GMAIL_LOGIN_FAILED,
    PASSWORD_RECOVERY_REQUESTED,
    PASSWORD_RESET_SUCCESS,
    PASSWORD_RESET_FAILED,
    REFEREE_CREATED,
    ORGANIZER_CREATED,
    TOKEN_REFRESHED,
    TOKEN_REFRESH_FAILED,
    LOGOUT_SUCCESS,
    LOGOUT_FAILED
}
