package co.edu.escuelaing.techcup.identity.document;

import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Represents an auditable event generated by the Identity Service.
 * Events are stored in the MongoDB audit_events collection.
 */
@Document(collection = "audit_events")
public class AuditEventDocument {

    @Id
    private UUID id;

    @CreatedDate
    @Indexed
    private LocalDateTime timestamp;

    @Indexed
    private UUID userId;

    private String actorEmail;

    @Indexed
    private AuditEventType eventType;

    private AuditResult result;

    private String description;

    private String detail;

    public AuditEventDocument() {
    }

    private AuditEventDocument(Builder builder) {
        this.id = builder.id != null ? builder.id : UUID.randomUUID();
        this.timestamp = builder.timestamp;
        this.userId = builder.userId;
        this.actorEmail = builder.actorEmail;
        this.eventType = builder.eventType;
        this.result = builder.result;
        this.description = builder.description;
        this.detail = builder.detail;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private UUID id;
        private LocalDateTime timestamp;
        private UUID userId;
        private String actorEmail;
        private AuditEventType eventType;
        private AuditResult result;
        private String description;
        private String detail;

        public Builder id(UUID id) {
            this.id = id;
            return this;
        }

        public Builder timestamp(LocalDateTime timestamp) {
            this.timestamp = timestamp;
            return this;
        }

        public Builder userId(UUID userId) {
            this.userId = userId;
            return this;
        }

        public Builder actorEmail(String actorEmail) {
            this.actorEmail = actorEmail;
            return this;
        }

        public Builder eventType(AuditEventType eventType) {
            this.eventType = eventType;
            return this;
        }

        public Builder result(AuditResult result) {
            this.result = result;
            return this;
        }

        public Builder description(String description) {
            this.description = description;
            return this;
        }

        public Builder detail(String detail) {
            this.detail = detail;
            return this;
        }

        public AuditEventDocument build() {
            return new AuditEventDocument(this);
        }
    }

    public UUID getId() {
        return id;
    }

    public LocalDateTime getTimestamp() {
        return timestamp;
    }

    public UUID getUserId() {
        return userId;
    }

    public String getActorEmail() {
        return actorEmail;
    }

    public AuditEventType getEventType() {
        return eventType;
    }

    public AuditResult getResult() {
        return result;
    }

    public String getDescription() {
        return description;
    }

    public String getDetail() {
        return detail;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public void setTimestamp(LocalDateTime timestamp) {
        this.timestamp = timestamp;
    }

    public void setUserId(UUID userId) {
        this.userId = userId;
    }

    public void setActorEmail(String actorEmail) {
        this.actorEmail = actorEmail;
    }

    public void setEventType(AuditEventType eventType) {
        this.eventType = eventType;
    }

    public void setResult(AuditResult result) {
        this.result = result;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void setDetail(String detail) {
        this.detail = detail;
    }
}