#verrides the base config for local development. It points to a local PostgreSQL database, configures Mailtrap as a fake email server 
#(so OTP emails don't send for real), and enables verbose logging for debugging.

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/identity_db
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: ${MAIL_USER:tu_usuario_mailtrap}
    password: ${MAIL_PASS:tu_password_mailtrap}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    co.edu.escuelaing.techcup: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
