#This is is the Spring Boot configuration file.
#It defines runtime settings, server port, database connection, JWT secret, email server, and logging levels
#between dev, prod and test, so each environment uses the right values without changing code

spring:
  application:
    name: service-identity
  profiles:
    active: dev
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid,email,profile

server:

#CONFIRM PORT WITH THE OTHER MICROSERVICES TEAMS
  port: 11711

app:
  jwt:
    secret: ${JWT_SECRET:super-secret-key-that-is-at-least-256-bits-long-for-hs256}
    expiration-ms: 900000        # 15 min
    refresh-expiration-ms: 604800000  # 7 days
  otp:
    expiration-minutes: 5
    length: 6
